import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { RecommendationRow, RecommendationStatus } from '../../types/cpi';
import { api } from '../../shared/api/client';
import { useAuth } from '../auth/AuthContext';
import {
  FileCheck,
  CheckCircle2,
  XCircle,
  Clock,
  Sparkles,
  ExternalLink,
  Shield,
  RefreshCw,
  ArrowRight,
} from 'lucide-react';

export const RecommendationsPage: React.FC = () => {
  const { canApproveReject, role } = useAuth();
  const [recommendations, setRecommendations] = useState<RecommendationRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedStatus, setSelectedStatus] = useState<string>('all');
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  const fetchRecommendations = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.getRecommendations();
      setRecommendations(res.items || []);
    } catch (err: unknown) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError('Failed to fetch recommendations');
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, []);

  const handleStatusUpdate = async (id: string, newStatus: RecommendationStatus) => {
    setActionLoading(id);
    try {
      await api.updateRecommendationStatus(id, newStatus);
      // Update local state
      setRecommendations((prev) =>
        prev.map((r) => (r.recommendation_id === id ? { ...r, status: newStatus } : r))
      );
    } catch (err: unknown) {
      alert(err instanceof Error ? err.message : 'Action failed');
    } finally {
      setActionLoading(null);
    }
  };

  const filtered = recommendations.filter((r) => {
    if (selectedStatus === 'all') return true;
    return r.status.toLowerCase() === selectedStatus.toLowerCase();
  });

  const getStatusBadge = (status: string) => {
    switch (status.toLowerCase()) {
      case 'approved':
        return (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800 border border-emerald-200 shadow-2xs">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            Approved
          </span>
        );
      case 'rejected':
        return (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-red-100 text-red-800 border border-red-200 shadow-2xs">
            <XCircle className="w-4 h-4 text-red-600 shrink-0" />
            Rejected
          </span>
        );
      case 'draft':
      default:
        return (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-amber-100 text-amber-800 border border-amber-200 shadow-2xs">
            <Clock className="w-4 h-4 text-amber-600 shrink-0" />
            Pending Review
          </span>
        );
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-stone-200">
        <div>
          <h1 className="text-2xl sm:text-3xl font-display font-bold text-stone-900 tracking-tight">
            Recommendation Inbox & Approvals
          </h1>
          <p className="text-sm text-stone-600 mt-1">
            Persisted optimization roadmaps generated by the ARG Engine • Human-in-the-Loop Review
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={fetchRecommendations}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-bold text-stone-700 bg-white border border-stone-300 hover:bg-stone-50 shadow-2xs"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            <span>Refresh</span>
          </button>
        </div>
      </div>

      {/* Role Notice */}
      {!canApproveReject && (
        <div className="p-4 bg-stone-100 border border-stone-200 rounded-2xl text-xs text-stone-700 flex items-center justify-between">
          <span className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-stone-500 shrink-0" />
            <span>
              Your current role (<strong className="capitalize">{role}</strong>) is read-only for approvals. Log in as <strong>Admin</strong> to approve or reject recommendations.
            </span>
          </span>
        </div>
      )}

      {/* Filter Tabs */}
      <div className="flex items-center gap-2 border-b border-stone-200 pb-3 overflow-x-auto">
        {['all', 'draft', 'approved', 'rejected'].map((s) => (
          <button
            key={s}
            onClick={() => setSelectedStatus(s)}
            className={`px-3.5 py-1.5 rounded-lg text-xs font-bold capitalize transition-colors ${
              selectedStatus === s
                ? 'bg-slate-900 text-white shadow-xs'
                : 'text-stone-600 hover:bg-stone-100'
            }`}
          >
            {s === 'draft' ? 'Pending (Draft)' : s}
          </button>
        ))}
      </div>

      {/* Content List */}
      {loading ? (
        <div className="space-y-4">
          {[1, 2, 3].map((i) => (
            <div key={i} className="bg-white rounded-2xl border border-stone-200 p-6 animate-pulse space-y-3">
              <div className="h-5 w-48 bg-stone-200 rounded" />
              <div className="h-4 w-3/4 bg-stone-100 rounded" />
              <div className="h-20 bg-stone-50 rounded" />
            </div>
          ))}
        </div>
      ) : error ? (
        <div className="p-8 text-center bg-white rounded-2xl border border-red-200">
          <p className="text-sm text-red-600 mb-3">{error}</p>
          <button
            onClick={fetchRecommendations}
            className="px-4 py-2 bg-slate-900 text-white rounded-lg text-xs font-semibold"
          >
            Retry
          </button>
        </div>
      ) : filtered.length === 0 ? (
        <div className="p-12 text-center bg-white rounded-2xl border border-stone-200 space-y-3">
          <FileCheck className="w-12 h-12 text-stone-400 mx-auto" />
          <h3 className="text-base font-bold text-stone-800">No recommendations yet</h3>
          <p className="text-xs text-stone-500 max-w-sm mx-auto">
            Open any creative in the library and run <strong>Analyse → Recommend</strong> to formulate persistent optimization plans.
          </p>
          <Link
            to="/creatives"
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-900 text-white text-xs font-bold mt-2 hover:bg-slate-800"
          >
            <span>Go to Creatives Library</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      ) : (
        <div className="space-y-4">
          {filtered.map((rec) => {
            const payload = rec.payload as {
              stage?: string;
              diagnosis?: { summary?: string; findings?: Array<{ claim: string }> };
              recommend?: { summary?: string; items?: Array<{ action: string; priority: string; reason: string }> };
            } | null;

            return (
              <motion.div
                key={rec.recommendation_id}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-white rounded-2xl border border-stone-200 p-5 sm:p-7 shadow-xs space-y-4 hover:border-slate-300 transition-colors"
              >
                {/* Header: ID, Creative ID, Status, Timestamp */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-stone-100">
                  <div className="flex items-center gap-2.5 flex-wrap">
                    <span className="font-mono text-xs font-bold px-2.5 py-1 rounded bg-stone-100 text-stone-800">
                      {rec.recommendation_id}
                    </span>
                    <Link
                      to={`/creatives/${rec.creative_id}`}
                      className="text-xs font-bold text-slate-900 hover:text-amber-700 hover:underline flex items-center gap-1"
                    >
                      <span>Creative: {rec.creative_id}</span>
                      <ExternalLink className="w-3.5 h-3.5" />
                    </Link>
                  </div>

                  <div className="flex items-center gap-3">
                    <span className="text-xs text-stone-400 font-mono">
                      {new Date(rec.created_at).toLocaleString()}
                    </span>
                    {getStatusBadge(rec.status)}
                  </div>
                </div>

                {/* Body Content from Payload */}
                <div className="space-y-3.5">
                  {payload?.recommend?.summary && (
                    <div className="p-4 bg-amber-500/10 border border-amber-500/30 rounded-xl text-xs text-stone-900 font-medium leading-relaxed">
                      "{payload.recommend.summary}"
                    </div>
                  )}

                  {/* Recommendation Action Items */}
                  {payload?.recommend?.items && (
                    <div className="space-y-2.5">
                      <h4 className="text-xs font-bold uppercase tracking-wider text-stone-400">
                        Proposed Interventions ({payload.recommend.items.length})
                      </h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        {payload.recommend.items.map((item, idx) => (
                          <div
                            key={idx}
                            className="p-4 bg-stone-50 rounded-xl border border-stone-200 text-xs space-y-1.5"
                          >
                            <div className="flex items-center justify-between">
                              <span className="font-bold text-stone-900">{item.action}</span>
                              <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-stone-200 text-stone-800">
                                {item.priority}
                              </span>
                            </div>
                            <p className="text-xs text-stone-600 leading-relaxed">{item.reason}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>

                {/* Admin Approval Actions */}
                {canApproveReject && (
                  <div className="pt-3 border-t border-stone-100 flex items-center justify-end gap-2.5">
                    <button
                      onClick={() => handleStatusUpdate(rec.recommendation_id, 'rejected')}
                      disabled={actionLoading === rec.recommendation_id || rec.status === 'rejected'}
                      className="px-4 py-2 rounded-xl text-xs font-bold text-red-700 bg-red-50 hover:bg-red-100 border border-red-200 transition-colors disabled:opacity-40 flex items-center gap-1.5"
                    >
                      <XCircle className="w-4 h-4" />
                      <span>Reject</span>
                    </button>

                    <button
                      onClick={() => handleStatusUpdate(rec.recommendation_id, 'approved')}
                      disabled={actionLoading === rec.recommendation_id || rec.status === 'approved'}
                      className="px-4 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 hover:bg-emerald-100 border border-emerald-200 transition-colors disabled:opacity-40 flex items-center gap-1.5"
                    >
                      <CheckCircle2 className="w-4 h-4" />
                      <span>Approve</span>
                    </button>
                  </div>
                )}
              </motion.div>
            );
          })}
        </div>
      )}
    </div>
  );
};
