import {
  AuthUser,
  BrandKitRow,
  BrandRow,
  CreativeBundle,
  CreativeListItem,
  GenerationRow,
  LeadRow,
  RecommendationRow,
  AnalyseRecommendGenerateResult
} from '../../types/cpi';

export const MOCK_USERS: Record<string, { password: string; user: AuthUser }> = {
  'admin@cpi.demo': {
    password: 'Admin123!',
    user: {
      user_id: 'user_admin_demo',
      email: 'admin@cpi.demo',
      role: 'admin',
      display_name: 'Demo Admin',
    },
  },
  'analyst@cpi.demo': {
    password: 'Analyst123!',
    user: {
      user_id: 'user_analyst_demo',
      email: 'analyst@cpi.demo',
      role: 'analyst',
      display_name: 'Pooja (Sr. Growth Analyst)',
    },
  },
  'viewer@cpi.demo': {
    password: 'Viewer123!',
    user: {
      user_id: 'user_viewer_demo',
      email: 'viewer@cpi.demo',
      role: 'viewer',
      display_name: 'Rohan (Brand Viewer)',
    },
  },
};

export const MOCK_BRAND: BrandRow = {
  brand_id: 'brand_mm_mithaiwala',
  name: 'Aura Lifestyle Store',
  tagline: "Curated premium essentials for modern living & celebration",
  provenance: 'synthetic',
  created_at: '2026-08-25T00:00:00.000Z',
  updated_at: '2026-08-25T00:00:00.000Z',
};

export const MOCK_BRAND_KIT: BrandKitRow = {
  brand_id: 'brand_mm_mithaiwala',
  colours: {
    primary: '#1E293B',
    secondary: '#D97706',
    accent: '#F59E0B',
    background: '#F8FAFC',
    text: '#0F172A',
  },
  fonts: {
    display: 'Playfair Display',
    body: 'Source Sans 3',
  },
  tone: [
    'modern premium',
    'curated luxury',
    'warm & welcoming',
    'lifestyle-forward',
    'authentic & elevated',
  ],
  must_include: [
    'brand emblem or logo clarity',
    'hero product clearly visible in first 1.5s',
    'clear value proposition or craftsmanship note',
  ],
  must_avoid: [
    'cheap discount screaming badges',
    'cluttered typography overlays',
    'unverified superlative claims',
    'harsh strobe animations',
  ],
  cta_preferences: [
    'ORDER_NOW',
    'SHOP_NOW',
    'SEND_WHATSAPP',
  ],
  markets: [
    'Metro Pan-India Delivery',
    'Tier-1 Urban Centers',
    'Express Same-Day Delivery Hubs',
    'Global NRI Express Shipping',
  ],
  logo_path: 'storage/brand/aura_logo.svg',
  created_at: '2026-08-25T00:00:00.000Z',
  updated_at: '2026-08-25T00:00:00.000Z',
};

export const MOCK_CREATIVES_LIST: CreativeListItem[] = [
  {
    creative_id: 'cr_476183_01',
    campaign_id: 'camp_seasonal_outreach_2026',
    format: 'video',
    concept: 'festive_event',
    cta: 'SEND_WHATSAPP',
    product_theme: 'curated_gift_box',
    headline: 'Curated Signature Hampers for Every Celebration',
    provenance: 'synthetic',
    campaign: {
      campaign_id: 'camp_seasonal_outreach_2026',
      name: 'Seasonal Lifestyle Outreach & Concierge Orders',
    },
  },
  {
    creative_id: 'cr_476183_02',
    campaign_id: 'camp_corporate_gifting_2026',
    format: 'static',
    concept: 'corporate_gifting',
    cta: 'ORDER_NOW',
    product_theme: 'luxury_gift_collection',
    headline: 'Bespoke Executive Gift Boxes — Redefining Premium Gifting',
    provenance: 'synthetic',
    campaign: {
      campaign_id: 'camp_corporate_gifting_2026',
      name: 'B2B & Executive Corporate Gifting',
    },
  },
  {
    creative_id: 'cr_476183_03',
    campaign_id: 'camp_lifestyle_classics_2026',
    format: 'carousel',
    concept: 'product_hero',
    cta: 'SHOP_NOW',
    product_theme: 'artisan_home_essentials',
    headline: 'Handcrafted Living & Artisanal Decor for Modern Homes',
    provenance: 'synthetic',
    campaign: {
      campaign_id: 'camp_lifestyle_classics_2026',
      name: 'Artisan Essentials Brand Campaign',
    },
  },
  {
    creative_id: 'cr_476183_04',
    campaign_id: 'camp_social_proof_2026',
    format: 'video',
    concept: 'social_proof',
    cta: 'SEND_WHATSAPP',
    product_theme: 'premium_lifestyle_set',
    headline: 'Over 50,000 Verified Customers Trust Aura Lifestyle',
    provenance: 'synthetic',
    campaign: {
      campaign_id: 'camp_social_proof_2026',
      name: 'Customer Stories & Community Proof',
    },
  },
];

export const MOCK_BUNDLES: Record<string, CreativeBundle> = {
  'cr_476183_01': {
    creative: {
      creative_id: 'cr_476183_01',
      campaign_id: 'camp_seasonal_outreach_2026',
      library_id: '476183_meta_lib_01',
      format: 'video',
      video_duration_seconds: 15,
      source_tag: 'owned',
      concept: 'festive_event',
      cta: 'SEND_WHATSAPP',
      destination: 'whatsapp',
      product_theme: 'curated_gift_box',
      primary_text: "Elevate your celebrations with our signature handcrafted lifestyle collection. Express delivery with bespoke personalization. Chat with our concierge team on WhatsApp for custom curation.",
      headline: 'Curated Signature Hampers for Every Celebration',
      description: 'Handcrafted luxury assortments with artisan delights, scented soy candles & organic treats.',
      started_running_on: '2026-08-01',
      media_path: null,
      provenance: 'synthetic',
      copy_provenance: 'synthetic',
      performance_provenance: 'synthetic',
    },
    campaign: {
      campaign_id: 'camp_seasonal_outreach_2026',
      brand_id: 'brand_mm_mithaiwala',
      name: 'Seasonal Lifestyle Outreach & Concierge Orders',
      objective_hint: 'messages',
      provenance: 'synthetic',
    },
    brand: MOCK_BRAND,
    content_matrix: {
      creative_id: 'cr_476183_01',
      tone: 'elevated_warm',
      logo_clarity: 4,
      has_human_figure: true,
      has_price_badge: false,
      hook_seconds: '1.50',
      cta_in_asset: 'WhatsApp us for instant concierge curation',
      cta_timing_seconds: '8.00',
      presenter: 'product_hero',
      colour_hue_primary: 'slate_amber',
      colour_palette: ['#1E293B', '#D97706', '#F59E0B', '#F8FAFC'],
      font_style: 'serif_display',
      font_size_relative: 'large',
      seconds_per_scene: [3, 4, 5, 3],
      script_summary: 'Open on bespoke gift hamper reveal → macro lens product textures → unboxing & styling moment → WhatsApp CTA banner with direct order prompt',
      model_version: 'matrix_v2.4',
      provenance: 'synthetic',
      created_at: '2026-08-25T00:00:00.000Z',
      updated_at: '2026-08-25T00:00:00.000Z',
    },
    video_dropoff: {
      creative_id: 'cr_476183_01',
      duration_seconds: 15,
      curve: [
        { t: 0, retention: 1.0 },
        { t: 1, retention: 0.88 },
        { t: 2, retention: 0.79 },
        { t: 3, retention: 0.72 },
        { t: 5, retention: 0.61 },
        { t: 8, retention: 0.52 },
        { t: 10, retention: 0.44 },
        { t: 12, retention: 0.38 },
        { t: 15, retention: 0.31 },
      ],
      provenance: 'synthetic',
      created_at: '2026-08-25T00:00:00.000Z',
      updated_at: '2026-08-25T00:00:00.000Z',
    },
    metrics_daily: [
      {
        creative_id: 'cr_476183_01',
        metric_date: '2026-08-18',
        campaign_id: 'camp_seasonal_outreach_2026',
        impressions: 12000,
        reach: 9800,
        clicks: 340,
        ctr: '0.0283',
        cpc_inr: '12.50',
        spend_inr: '4250.00',
        thumb_stop_rate: '0.3100',
        hook_rate_3s: '0.2800',
        video_p25: '0.5500',
        video_p50: '0.4000',
        video_p75: '0.2800',
        video_p100: '0.1800',
        messaging_conversations_started: 42,
        purchases: 3,
        adds_to_cart: 8,
        landing_page_views: 90,
        results_roas: '1.8500',
        provenance: 'synthetic',
      },
      {
        creative_id: 'cr_476183_01',
        metric_date: '2026-08-19',
        campaign_id: 'camp_seasonal_outreach_2026',
        impressions: 13500,
        reach: 10400,
        clicks: 380,
        ctr: '0.0281',
        cpc_inr: '11.80',
        spend_inr: '4484.00',
        thumb_stop_rate: '0.3200',
        hook_rate_3s: '0.2900',
        video_p25: '0.5600',
        video_p50: '0.4100',
        video_p75: '0.2900',
        video_p100: '0.1900',
        messaging_conversations_started: 48,
        purchases: 4,
        adds_to_cart: 11,
        landing_page_views: 104,
        results_roas: '1.9200',
        provenance: 'synthetic',
      },
      {
        creative_id: 'cr_476183_01',
        metric_date: '2026-08-20',
        campaign_id: 'camp_seasonal_outreach_2026',
        impressions: 11800,
        reach: 9200,
        clicks: 310,
        ctr: '0.0263',
        cpc_inr: '13.20',
        spend_inr: '4092.00',
        thumb_stop_rate: '0.3000',
        hook_rate_3s: '0.2600',
        video_p25: '0.5300',
        video_p50: '0.3900',
        video_p75: '0.2700',
        video_p100: '0.1700',
        messaging_conversations_started: 38,
        purchases: 2,
        adds_to_cart: 7,
        landing_page_views: 82,
        results_roas: '1.7100',
        provenance: 'synthetic',
      },
      {
        creative_id: 'cr_476183_01',
        metric_date: '2026-08-21',
        campaign_id: 'camp_seasonal_outreach_2026',
        impressions: 14200,
        reach: 11100,
        clicks: 410,
        ctr: '0.0289',
        cpc_inr: '12.00',
        spend_inr: '4920.00',
        thumb_stop_rate: '0.3300',
        hook_rate_3s: '0.3000',
        video_p25: '0.5700',
        video_p50: '0.4200',
        video_p75: '0.3000',
        video_p100: '0.2000',
        messaging_conversations_started: 54,
        purchases: 5,
        adds_to_cart: 14,
        landing_page_views: 118,
        results_roas: '2.0500',
        provenance: 'synthetic',
      },
      {
        creative_id: 'cr_476183_01',
        metric_date: '2026-08-22',
        campaign_id: 'camp_seasonal_outreach_2026',
        impressions: 16000,
        reach: 12500,
        clicks: 470,
        ctr: '0.0294',
        cpc_inr: '11.50',
        spend_inr: '5405.00',
        thumb_stop_rate: '0.3400',
        hook_rate_3s: '0.3100',
        video_p25: '0.5800',
        video_p50: '0.4400',
        video_p75: '0.3100',
        video_p100: '0.2100',
        messaging_conversations_started: 62,
        purchases: 6,
        adds_to_cart: 16,
        landing_page_views: 135,
        results_roas: '2.1800',
        provenance: 'synthetic',
      },
    ],
    targeting_stats: [
      {
        id: 1,
        creative_id: 'cr_476183_01',
        metric_date: '2026-08-22',
        audience_type: 'lifestyle_shoppers',
        age_bucket: '25-34',
        gender: 'all',
        geo: 'Metro Urban Centers',
        placement: 'instagram_feed',
        impressions: 6500,
        clicks: 210,
        spend_inr: '2415.00',
        messaging_conversations_started: 28,
        purchases: 3,
        provenance: 'synthetic',
      },
      {
        id: 2,
        creative_id: 'cr_476183_01',
        metric_date: '2026-08-22',
        audience_type: 'curated_gifts_interest',
        age_bucket: '30-50',
        gender: 'all',
        geo: 'Tier-1 Metros',
        placement: 'facebook_feed',
        impressions: 5500,
        clicks: 160,
        spend_inr: '1840.00',
        messaging_conversations_started: 22,
        purchases: 2,
        provenance: 'synthetic',
      },
    ],
  },
  'cr_476183_02': {
    creative: {
      creative_id: 'cr_476183_02',
      campaign_id: 'camp_corporate_gifting_2026',
      library_id: '476183_meta_lib_02',
      format: 'static',
      video_duration_seconds: null,
      source_tag: 'owned',
      concept: 'corporate_gifting',
      cta: 'ORDER_NOW',
      destination: 'landing_page',
      product_theme: 'luxury_gift_collection',
      primary_text: 'Leave a lasting impression with custom corporate gifting. Curated artisan delights in bespoke matte gold gift boxes with your organization branding.',
      headline: 'Bespoke Executive Gift Boxes — Redefining Premium Gifting',
      description: 'Volume corporate pricing, temperature-controlled shipping & bespoke company embossing.',
      started_running_on: '2026-08-05',
      media_path: null,
      provenance: 'synthetic',
      copy_provenance: 'synthetic',
      performance_provenance: 'synthetic',
    },
    campaign: {
      campaign_id: 'camp_corporate_gifting_2026',
      brand_id: 'brand_mm_mithaiwala',
      name: 'B2B & Executive Corporate Gifting',
      objective_hint: 'leads',
      provenance: 'synthetic',
    },
    brand: MOCK_BRAND,
    content_matrix: {
      creative_id: 'cr_476183_02',
      tone: 'executive_luxury',
      logo_clarity: 5,
      has_human_figure: false,
      has_price_badge: true,
      hook_seconds: null,
      cta_in_asset: 'Request Corporate Catalogue',
      cta_timing_seconds: null,
      presenter: 'product_hero',
      colour_hue_primary: 'slate_gold',
      colour_palette: ['#1E293B', '#D97706', '#F8FAFC', '#334155'],
      font_style: 'serif_display',
      font_size_relative: 'xlarge',
      seconds_per_scene: null,
      script_summary: 'Clean modern flat-lay of handcrafted gift sets on marble stone, subtle gold embossed packaging corner.',
      model_version: 'matrix_v2.4',
      provenance: 'synthetic',
    },
    video_dropoff: null,
    metrics_daily: [
      {
        creative_id: 'cr_476183_02',
        metric_date: '2026-08-20',
        campaign_id: 'camp_corporate_gifting_2026',
        impressions: 8900,
        reach: 7100,
        clicks: 290,
        ctr: '0.0326',
        cpc_inr: '18.40',
        spend_inr: '5336.00',
        thumb_stop_rate: '0.3800',
        hook_rate_3s: null,
        video_p25: null,
        video_p50: null,
        video_p75: null,
        video_p100: null,
        messaging_conversations_started: 19,
        purchases: 6,
        adds_to_cart: 18,
        landing_page_views: 220,
        results_roas: '3.4000',
        provenance: 'synthetic',
      },
    ],
    targeting_stats: [
      {
        id: 4,
        creative_id: 'cr_476183_02',
        metric_date: '2026-08-20',
        audience_type: 'corporate_execs',
        age_bucket: '30-60',
        gender: 'all',
        geo: 'Metros & Urban Hubs',
        placement: 'facebook_feed',
        impressions: 8900,
        clicks: 290,
        spend_inr: '5336.00',
        messaging_conversations_started: 19,
        purchases: 6,
        provenance: 'synthetic',
      },
    ],
  },
};

export const MOCK_LEADS: LeadRow[] = [
  {
    lead_id: 'lead_001',
    brand_id: 'brand_mm_mithaiwala',
    creative_id: 'cr_476183_01',
    campaign_id: 'camp_seasonal_outreach_2026',
    name: 'Priya Sharma',
    phone: '+91 98201 44520',
    email: 'priya.sharma@horizoncorp.com',
    stage: 'new',
    ad_ref: 'ad_ref_lifestyle_01',
    source_channel: 'whatsapp',
    created_at: '2026-08-25T10:15:00.000Z',
    provenance: 'synthetic',
    updated_at: '2026-08-25T10:15:00.000Z',
  },
  {
    lead_id: 'lead_002',
    brand_id: 'brand_mm_mithaiwala',
    creative_id: 'cr_476183_01',
    campaign_id: 'camp_seasonal_outreach_2026',
    name: 'Anand Mehta',
    phone: '+91 98192 11940',
    email: 'anand.m@mehtaglobal.in',
    stage: 'engaged',
    ad_ref: 'ad_ref_lifestyle_01',
    source_channel: 'whatsapp',
    created_at: '2026-08-24T14:30:00.000Z',
    provenance: 'synthetic',
    updated_at: '2026-08-24T16:00:00.000Z',
  },
  {
    lead_id: 'lead_003',
    brand_id: 'brand_mm_mithaiwala',
    creative_id: 'cr_476183_02',
    campaign_id: 'camp_corporate_gifting_2026',
    name: 'Ritu Varma (Executive Gifting Desk)',
    phone: '+91 99208 77610',
    email: 'ritu.v@apextech.com',
    stage: 'intent',
    ad_ref: 'ad_ref_corp_gift_02',
    source_channel: 'lead_form',
    created_at: '2026-08-23T11:20:00.000Z',
    provenance: 'synthetic',
    updated_at: '2026-08-24T09:10:00.000Z',
  },
  {
    lead_id: 'lead_004',
    brand_id: 'brand_mm_mithaiwala',
    creative_id: 'cr_476183_02',
    campaign_id: 'camp_corporate_gifting_2026',
    name: 'Sameer Merchant',
    phone: '+91 97690 33810',
    email: 'sameer@merchantventures.com',
    stage: 'visit_booked',
    ad_ref: 'ad_ref_corp_gift_02',
    source_channel: 'lead_form',
    created_at: '2026-08-22T16:45:00.000Z',
    provenance: 'synthetic',
    updated_at: '2026-08-25T11:00:00.000Z',
  },
  {
    lead_id: 'lead_005',
    brand_id: 'brand_mm_mithaiwala',
    creative_id: 'cr_476183_01',
    campaign_id: 'camp_seasonal_outreach_2026',
    name: 'Kavita Patel',
    phone: '+91 98210 99420',
    email: 'kavita.patel@gmail.com',
    stage: 'visited',
    ad_ref: 'ad_ref_lifestyle_01',
    source_channel: 'whatsapp',
    created_at: '2026-08-21T09:30:00.000Z',
    provenance: 'synthetic',
    updated_at: '2026-08-23T15:20:00.000Z',
  },
  {
    lead_id: 'lead_006',
    brand_id: 'brand_mm_mithaiwala',
    creative_id: 'cr_476183_02',
    campaign_id: 'camp_corporate_gifting_2026',
    name: 'Deepak Joshi (Apex Retail)',
    phone: '+91 98670 12345',
    email: 'd.joshi@apexretail.in',
    stage: 'sale',
    ad_ref: 'ad_ref_corp_gift_02',
    source_channel: 'lead_form',
    created_at: '2026-08-20T13:10:00.000Z',
    provenance: 'synthetic',
    updated_at: '2026-08-25T14:40:00.000Z',
  },
];

export const MOCK_RECOMMENDATIONS: RecommendationRow[] = [
  {
    recommendation_id: 'rec_550e8400-e29b-41d4-a716-446655440000',
    creative_id: 'cr_476183_01',
    payload: {
      stage: 'generate',
      diagnosis: {
        creative_id: 'cr_476183_01',
        data_provenance: 'synthetic',
        analysed_at: '2026-08-26T04:00:00.000Z',
        summary: 'Hook rate is soft vs peers (0.28 vs 0.34 median); CTR is healthy at 2.83%; WhatsApp direct-to-chat CTA drives high engagement.',
        findings: [
          {
            severity: 'warn',
            area: 'hook',
            claim: '3s hook rate is below peer median for seasonal lifestyle creatives.',
            citations: ['metrics.avg_hook_rate_3s', 'peers.cr_476183_02'],
          },
          {
            severity: 'info',
            area: 'cta',
            claim: 'Direct WhatsApp CTA yields 42 conversation starts / day at ₹12.50 CPC.',
            citations: ['metrics.messaging_conversations_started', 'metrics.cpc_inr'],
          },
          {
            severity: 'critical',
            area: 'retention',
            claim: 'Significant 28% drop-off occurs between second 1 and second 3 before the complete collection is showcased.',
            citations: ['video_dropoff.curve', 'content_matrix.seconds_per_scene'],
          },
        ],
        metrics: {
          creative_id: 'cr_476183_01',
          days: 7,
          date_from: '2026-08-18',
          date_to: '2026-08-24',
          impressions: 84000,
          reach: 62000,
          clicks: 2100,
          spend_inr: 28500.5,
          avg_ctr: 0.025,
          avg_cpc_inr: 13.57,
          avg_thumb_stop_rate: 0.31,
          avg_hook_rate_3s: 0.22,
          avg_video_p25: 0.55,
          avg_video_p50: 0.4,
          avg_video_p75: 0.28,
          avg_video_p100: 0.18,
          messaging_conversations_started: 260,
          purchases: 18,
          adds_to_cart: 40,
          landing_page_views: 520,
          avg_results_roas: 1.85,
          provenance: 'synthetic',
        },
        content_matrix: {
          tone: 'elevated_warm',
          logo_clarity: 4,
          hook_seconds: '1.50',
          colour_palette: ['#1E293B', '#D97706'],
          script_summary: 'Open on box reveal → product close-up → WhatsApp CTA',
        },
        similar_creatives: [
          {
            creative_id: 'cr_476183_02',
            concept: 'festive_event',
            cta: 'ORDER_NOW',
            product_theme: 'curated_gift_box',
            format: 'static',
            distance: 0.21,
            document_preview: 'Hero lifestyle box with gold accents and instant product reveal...',
          },
        ],
        llm_analysis_available: true,
        llm_analysis: {
          summary: 'Creative is mid-funnel efficient but loses attention in first 3s due to delayed hero item presentation.',
          strongest_elements: ['Clear WhatsApp concierge CTA badge', 'Sophisticated brand colors (#1E293B / #D97706)', 'High conversion once hooked'],
          weakest_elements: ['Slow unboxing opener lacks instant visual punch', 'Headline text overlay enters late at 3.5s'],
          findings: [
            {
              severity: 'medium',
              area: 'hook',
              observation: 'avg_hook_rate_3s is 0.22 over 7 days vs 0.31 category average.',
              interpretation: 'Closed packaging opening frame may not stop scroll for modern shoppers in fast-scrolling feeds.',
              evidence_citations: ['metrics.avg_hook_rate_3s', 'content_matrix.hook_seconds'],
            },
          ],
          recommendations: [
            {
              priority: 'high',
              recommendation: 'Lead with hero product in first 1.0 second with high-contrast ambient lighting.',
              reason: 'Hook underperforms peers with earlier sensory product reveal.',
              evidence_citations: ['metrics.avg_hook_rate_3s', 'peers.cr_476183_02'],
            },
          ],
          similar_creative_insights: [
            'Peer cr_476183_02 uses immediate hero macro with ORDER_NOW button, achieving 38% thumb-stop rate.',
          ],
          next_tests: [
            'A/B first frame: Instant product macro vs packaging reveal',
            'Swap CTA copy: "Chat with Stylist" vs "Order on WhatsApp"',
          ],
        },
        llm_error: null,
      },
      recommend: {
        creative_id: 'cr_476183_01',
        summary: 'Tighten the opening hook to under 1s, emphasize artisan craftsmanship, and preserve the high-performing WhatsApp direct concierge CTA.',
        items: [
          {
            priority: 'high',
            action: 'Cut directly to close-up product hero within the first 1.0 second.',
            reason: 'Hook rate lags peer set when opening on closed packaging.',
            evidence_citations: ['metrics.avg_hook_rate_3s', 'video_dropoff.curve'],
            kind: 'fact_based',
          },
          {
            priority: 'medium',
            action: 'Add brand watermark emblem in top-left frame.',
            reason: 'Brand recognition aids thumb-stop on premium lifestyle audience segments.',
            evidence_citations: ['content_matrix.logo_clarity', 'brand.must_include'],
            kind: 'inference',
          },
          {
            priority: 'low',
            action: 'A/B test ORDER_NOW vs SEND_WHATSAPP CTA button overlay.',
            reason: 'Identify whether high-intent festive buyers prefer direct checkout over chat assistance.',
            evidence_citations: ['peers.cr_476183_02', 'brand.cta_preferences'],
            kind: 'inference',
          },
        ],
        next_tests: [
          'A/B first frame product macro vs packaging reveal',
          'CTA ORDER_NOW vs SEND_WHATSAPP for weekend collection drop',
        ],
        source: 'deterministic',
        created_at: '2026-08-26T04:00:01.000Z',
      },
    },
    citations: ['metrics.avg_hook_rate_3s', 'peers.cr_476183_02', 'video_dropoff.curve'],
    status: 'draft',
    created_at: '2026-08-26T04:00:01.000Z',
    updated_at: '2026-08-26T04:00:01.000Z',
  },
];

export const MOCK_GENERATIONS: GenerationRow[] = [
  {
    generation_id: 'gen_11111111-1111-1111-1111-111111111111',
    recommendation_id: 'rec_550e8400-e29b-41d4-a716-446655440000',
    type: 'copy',
    content: JSON.stringify({
      type: 'copy',
      headline: "Curated Signature Hampers — Message Us for Express Personalization",
      primary_text: "Handcrafted artisan collections for your most cherished moments. Skip the wait — connect with our concierge directly on WhatsApp.",
      cta: 'SEND_WHATSAPP',
      status: 'draft',
      evidence_citations: ['recommend.items[0]', 'brand.cta_preferences', 'brand.tone'],
    }),
    media_path: null,
    status: 'draft',
    created_at: '2026-08-26T04:00:02.000Z',
    updated_at: '2026-08-26T04:00:02.000Z',
  },
  {
    generation_id: 'gen_22222222-2222-2222-2222-222222222222',
    recommendation_id: 'rec_550e8400-e29b-41d4-a716-446655440000',
    type: 'concept',
    content: JSON.stringify({
      type: 'concept',
      concept_notes: "0-1s: Ultra macro slow-motion cut of handcrafted collection textures. 1-4s: Elegant gold logo lockup and bespoke box reveal. 4-8s: Warm lifestyle styling and gifting moment. 8-15s: High-contrast WhatsApp CTA banner 'Chat & Curate in 60s'.",
      status: 'draft',
      evidence_citations: ['content_matrix.script_summary', 'recommend.items[0]'],
    }),
    media_path: null,
    status: 'draft',
    created_at: '2026-08-26T04:00:02.000Z',
    updated_at: '2026-08-26T04:00:02.000Z',
  },
  {
    generation_id: 'gen_33333333-3333-3333-3333-333333333333',
    recommendation_id: 'rec_550e8400-e29b-41d4-a716-446655440000',
    type: 'static_image',
    content: JSON.stringify({
      type: 'static_image',
      image_prompt: "Luxury lifestyle gift hamper on warm white Italian marble, slate (#1E293B) and champagne gold (#D97706) ribbon accents, minimalist brand emblem badge top-left, soft warm morning sunlight, shallow depth of field, handcrafted artisan delicacies and home decor pieces, 8k commercial editorial photography, no discount badges or text overlays",
      status: 'draft',
      evidence_citations: ['brand.colours', 'recommend.items[0]', 'brand.must_include'],
    }),
    media_path: null,
    status: 'draft',
    created_at: '2026-08-26T04:00:02.000Z',
    updated_at: '2026-08-26T04:00:02.000Z',
  },
];

export function buildArgMockResult(
  creativeId: string,
  stage: 'analyse' | 'recommend' | 'generate',
  useLlm = true
): AnalyseRecommendGenerateResult {
  const baseDiagnosis = {
    creative_id: creativeId,
    data_provenance: 'synthetic',
    analysed_at: new Date().toISOString(),
    summary: 'Hook rate is soft vs peers (0.28 vs 0.34 median); CTR is healthy at 2.83%; WhatsApp direct-to-chat CTA drives high engagement.',
    findings: [
      {
        severity: 'warn' as const,
        area: 'hook',
        claim: '3s hook rate is below peer median for seasonal lifestyle creatives.',
        citations: ['metrics.avg_hook_rate_3s', 'peers.cr_476183_02'],
      },
      {
        severity: 'info' as const,
        area: 'cta',
        claim: 'Direct WhatsApp CTA yields 42 conversation starts / day at ₹12.50 CPC.',
        citations: ['metrics.messaging_conversations_started', 'metrics.cpc_inr'],
      },
      {
        severity: 'critical' as const,
        area: 'retention',
        claim: 'Significant 28% drop-off occurs between second 1 and second 3 before the full hamper assortment is revealed.',
        citations: ['video_dropoff.curve', 'content_matrix.seconds_per_scene'],
      },
    ],
    metrics: {
      creative_id: creativeId,
      days: 7,
      date_from: '2026-08-18',
      date_to: '2026-08-24',
      impressions: 84000,
      reach: 62000,
      clicks: 2100,
      spend_inr: 28500.5,
      avg_ctr: 0.025,
      avg_cpc_inr: 13.57,
      avg_thumb_stop_rate: 0.31,
      avg_hook_rate_3s: 0.22,
      avg_video_p25: 0.55,
      avg_video_p50: 0.4,
      avg_video_p75: 0.28,
      avg_video_p100: 0.18,
      messaging_conversations_started: 260,
      purchases: 18,
      adds_to_cart: 40,
      landing_page_views: 520,
      avg_results_roas: 1.85,
      provenance: 'synthetic',
    },
    content_matrix: {
      tone: 'elevated_warm',
      logo_clarity: 4,
      hook_seconds: '1.50',
      colour_palette: ['#1E293B', '#D97706'],
      script_summary: 'Open on box reveal → product close-up → WhatsApp CTA',
    },
    similar_creatives: [
      {
        creative_id: 'cr_476183_02',
        concept: 'festive_event',
        cta: 'ORDER_NOW',
        product_theme: 'curated_gift_box',
        format: 'static',
        distance: 0.21,
        document_preview: 'Hero lifestyle box with gold accents and instant product reveal...',
      },
    ],
    llm_analysis_available: useLlm,
    llm_analysis: useLlm
      ? {
          summary: 'Creative is mid-funnel efficient but loses attention in first 3s due to delayed hero item presentation.',
          strongest_elements: ['Clear WhatsApp concierge CTA badge', 'Sophisticated brand colors (#1E293B / #D97706)', 'High conversion once hooked'],
          weakest_elements: ['Slow unboxing opener lacks instant visual punch', 'Headline text overlay enters late at 3.5s'],
          findings: [
            {
              severity: 'medium' as const,
              area: 'hook',
              observation: 'avg_hook_rate_3s is 0.22 over 7 days vs 0.31 category average.',
              interpretation: 'Closed packaging opening frame may not stop scroll for modern shoppers in fast-scrolling feeds.',
              evidence_citations: ['metrics.avg_hook_rate_3s', 'content_matrix.hook_seconds'],
            },
          ],
          recommendations: [
            {
              priority: 'high' as const,
              recommendation: 'Lead with hero product in first 1.0 second with high-contrast ambient lighting.',
              reason: 'Hook underperforms peers with earlier sensory product reveal.',
              evidence_citations: ['metrics.avg_hook_rate_3s', 'peers.cr_476183_02'],
            },
          ],
          similar_creative_insights: [
            'Peer cr_476183_02 uses immediate hero macro with ORDER_NOW button, achieving 38% thumb-stop rate.',
          ],
          next_tests: [
            'A/B first frame: Instant product macro vs packaging reveal',
            'Swap CTA copy: "Chat with Stylist" vs "Order on WhatsApp"',
          ],
        }
      : null,
    llm_error: useLlm ? null : 'LLM disabled by user request',
  };

  const baseRecommend = {
    creative_id: creativeId,
    summary: 'Tighten the opening hook to under 1s, emphasize artisan craftsmanship, and preserve the high-performing WhatsApp direct concierge CTA.',
    items: [
      {
        priority: 'high' as const,
        action: 'Cut directly to close-up product hero within the first 1.0 second.',
        reason: 'Hook rate lags peer set when opening on closed packaging.',
        evidence_citations: ['metrics.avg_hook_rate_3s', 'video_dropoff.curve'],
        kind: 'fact_based' as const,
      },
      {
        priority: 'medium' as const,
        action: 'Add brand watermark emblem in top-left frame.',
        reason: 'Brand recognition aids thumb-stop on premium lifestyle audience segments.',
        evidence_citations: ['content_matrix.logo_clarity', 'brand.must_include'],
        kind: 'inference' as const,
      },
      {
        priority: 'low' as const,
        action: 'A/B test ORDER_NOW vs SEND_WHATSAPP CTA button overlay.',
        reason: 'Identify whether high-intent festive buyers prefer direct checkout over chat assistance.',
        evidence_citations: ['peers.cr_476183_02', 'brand.cta_preferences'],
        kind: 'inference' as const,
      },
    ],
    next_tests: [
      'A/B first frame product macro vs packaging reveal',
      'CTA ORDER_NOW vs SEND_WHATSAPP for weekend collection drop',
    ],
    source: useLlm ? ('llm' as const) : ('deterministic' as const),
    created_at: new Date().toISOString(),
  };

  const recId = `rec_${Date.now()}`;
  const genId1 = `gen_copy_${Date.now()}`;
  const genId2 = `gen_concept_${Date.now()}`;
  const genId3 = `gen_img_${Date.now()}`;

  const baseGenerate = {
    creative_id: creativeId,
    recommendation_id: recId,
    drafts: [
      {
        type: 'copy' as const,
        headline: "Curated Signature Hampers — Message Us for Express Personalization",
        primary_text: "Handcrafted artisan collections for your most cherished moments. Skip the wait — connect with our concierge directly on WhatsApp.",
        cta: 'SEND_WHATSAPP',
        status: 'draft' as const,
        evidence_citations: ['recommend.items[0]', 'brand.cta_preferences', 'brand.tone'],
      },
      {
        type: 'concept' as const,
        concept_notes: "0-1s: Ultra macro slow-motion cut of handcrafted collection textures. 1-4s: Elegant gold logo lockup and bespoke box reveal. 4-8s: Warm lifestyle styling and gifting moment. 8-15s: High-contrast WhatsApp CTA banner 'Chat & Curate in 60s'.",
        status: 'draft' as const,
        evidence_citations: ['content_matrix.script_summary', 'recommend.items[0]'],
      },
      {
        type: 'static_image' as const,
        image_prompt: "Luxury lifestyle gift hamper on warm white Italian marble, slate (#1E293B) and champagne gold (#D97706) ribbon accents, minimalist brand emblem badge top-left, soft warm morning sunlight, shallow depth of field, handcrafted artisan delicacies and home decor pieces, 8k commercial editorial photography, no discount badges or text overlays",
        status: 'draft' as const,
        evidence_citations: ['brand.colours', 'recommend.items[0]', 'brand.must_include'],
      },
    ],
    created_at: new Date().toISOString(),
  };

  if (stage === 'analyse') {
    return {
      stage: 'analyse',
      creative_id: creativeId,
      diagnosis: baseDiagnosis,
      recommend: null,
      generate: null,
      recommendation_id: null,
      generation_ids: [],
      next: 'recommend',
    };
  }

  if (stage === 'recommend') {
    return {
      stage: 'recommend',
      creative_id: creativeId,
      diagnosis: baseDiagnosis,
      recommend: baseRecommend,
      generate: null,
      recommendation_id: recId,
      generation_ids: [],
      next: 'generate',
    };
  }

  return {
    stage: 'generate',
    creative_id: creativeId,
    diagnosis: baseDiagnosis,
    recommend: baseRecommend,
    generate: baseGenerate,
    recommendation_id: recId,
    generation_ids: [genId1, genId2, genId3],
    next: 'approve',
  };
}
